import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Home/Navbar/Navbar";
import SmoothScrollProvider from "@/components/SmoothScrollProvider";

const font = Inter({
    weight: ["100", "200", "300", "400", "500", "700", "900"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
          className={`${font.className} antialiased`}
      >
      <SmoothScrollProvider>
          <Navbar />
          {children}
      </SmoothScrollProvider>

      </body>
    </html>
  );
}
